home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'

urlpatterns = [

    # Register User
    url(r'^register/$', views.register, name="register"),
    # - Get Information from user
    url(r'^information/$', views.get_information, name="get_information"),
    # - Dashboard
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    # /-Sends to home page
    url(r'^$', views.home_page, name="home_page"),

    # /schedule - Get Information from user
    url(r'^schedule/(?P<tournament_number>[0-9]+)/$', views.schedule, name="schedule"),
    # /test_send_email
    url(r'^test_send_email/$', views.test_send_email, name='test_send_email'),
    # /points_table/tournament number)/(pool_number) - Gets the points table
    url(r'^points_table/(?P<tournament_number>[0-9]+)/(?P<pool_number>[0-9]+)/$', views.points_table,
        name='points_table'),
    # /schedule/(tournament number)/(pool_number)
    url(r'^schedule/(?P<tournament_number>[0-9]+)/(?P<pool_number>[0-9]+)/$', views.schedule, name="pool_schedule"),
    # /logout
    url(r'^logout/$', views.logout, name="logout"),
    # /google_sign_in
    url(r'^google_sign_in/$', views.google_sign_in, name='google_sign_in'),

    url(r'^view/$', views.view_all_tournament, name='view_all_tournament'),

    url(r'^team/register/$', views.register_team, name='register_team'),

    url(r'^register/(?P<ref>.+)$', views.register, name="register"),

    url(r'^verification/email/(?P<key>[\w]+)/(?P<username>[\w]+)', views.verification_process,
        name="verification_process"),

    url(r'^verification/resend/$', views.resend_mail, name='resend_mail'),

    url(r'^start_scheduling/$', views.start_scheduling, name='start_scheduling'),

    url(r'^facebook_sign_in/$', views.facebook_sign_in, name='facebook_sign_in'),

    url(r'delete_tournament/(?P<id>[0-9]+)$', views.delete_tournament, name='delete_tournament'),
    url(r'^facebook_sign_in/$', views.facebook_sign_in, name='facebook_sign_in'),

    url(r'^change_password/$', views.change_password, name='change_password'),

    url(r'^forgot_password$', views.forgot_password, name='forgot_password'),

]

match_scheduler/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('home.urls')),
    url(r'^admin/', admin.site.urls),
    url('', include('social_django.urls', namespace='social')),
    url('', include('django.contrib.auth.urls', namespace='auth')),

]

home/models.py
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator
from django.db import models


# Create your models here.
class UserWrapper(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True)
    key = models.CharField(max_length=40)

    def __str__(self):
        return "User First Name: " + self.user.first_name + ", User Email: " + self.user.email


class Tournament(models.Model):
    login = models.ForeignKey(UserWrapper, on_delete=models.CASCADE)
    matches_per_day = models.PositiveIntegerField(validators=[MaxValueValidator(100)])
    number_of_team = models.IntegerField(validators=[MaxValueValidator(50)], default=0)
    number_of_pool = models.IntegerField(default=1)
    type = models.IntegerField()
    available_days = models.IntegerField()
    registration_ending = models.DateField()
    starting_date = models.DateField()
    sport = models.CharField(max_length=30)
    category = models.CharField(max_length=20, default="Open to all")

    def __str__(self):
        return "Tour. ID: " + str(self.id) + ', Type: ' + str(self.type) + ", tour. User: " + str(
            self.login) + ",tour.Category:" + (self.category)


class Pool(models.Model):
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE)
    pool_number = models.IntegerField(default=1)
    number_of_teams = models.IntegerField()

    def __str__(self):
        return str(self.tournament) + str(self.pool_number)


class Point(models.Model):
    pool = models.ForeignKey(Pool, on_delete=models.CASCADE, default=None)
    team = models.CharField(max_length=100)
    wins = models.IntegerField(default=0)

    def __str__(self):
        return str(self.team) + "-" + str(self.wins)


class Match(models.Model):
    pool = models.ForeignKey(Pool, on_delete=models.CASCADE, default=None)
    team1 = models.CharField(max_length=100)
    team2 = models.CharField(max_length=100)
    winner = models.CharField(max_length=1, default='0')

    def __str__(self):
        return str(self.pk) + self.team1 + "V/S" + self.team2 + "->" + self.winner


class GoogleUser(models.Model):
    user_wrapper = models.ForeignKey(UserWrapper)
    google_id = models.CharField(max_length=100)
    image_url = models.CharField(max_length=200)


class FacebookUser(models.Model):
    user_wrapper = models.ForeignKey(UserWrapper)
    fb_id = models.CharField(max_length=100)
    image_url = models.CharField(max_length=200)


class Team(models.Model):
    login = models.ForeignKey(UserWrapper, on_delete=models.CASCADE, blank=True)
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE, blank=True)
    team_name = models.CharField(max_length=100)

    def __str__(self):
        return str(self.team_name)


class Player(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    number = models.BigIntegerField()
    email = models.EmailField(max_length=100, blank=True, null=True)

    def __str__(self):
        return str("Team: " + str(self.team) + ", Name of Player: " + self.name)


class SportsSpecification(models.Model):
    no_of_players = models.PositiveIntegerField()
    sport = models.CharField(max_length=50)

    def __str__(self):
        return "No. of players: " + str(self.no_of_players) + ", sport: " + self.sport

home/views.py
import datetime
import hashlib
import json
import logging
import math
import random
import urllib
import facebook
import nexmo
from django.conf import settings
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render, HttpResponse, get_object_or_404, redirect
from django.utils.crypto import get_random_string

from home.conf import email_sending_service_enabled
from . import conf
from .forms import TournamentForm, UserForm, TeamForm, PlayerForm
from .models import Tournament, Point, UserWrapper, GoogleUser, Team, Player, Pool, Match, SportsSpecification, \
    FacebookUser
import datetime

logger = logging.getLogger(__name__)


def user_logged_in(request):
    user_id = request.session.get('user_id', 0)
    if not user_id:
        return 0
    else:
        return user_id


# Add a tournament
def get_information(request):
    user_id = user_logged_in(request)
    form = TournamentForm()
    # If user exists then he can add tournament

    if user_id:
        if request.method == "POST":
            user_obj = User.objects.get(pk=user_id)
            print(user_obj.userwrapper.key)
            if user_obj.userwrapper.key == 'verified':

                form = TournamentForm(request.POST)
                if form.is_valid():

                    user_wrapper = user_obj.userwrapper

                    logger.debug(user_wrapper.user.username)
                    type_of_match = form.cleaned_data.get('match_type')
                    avalaible_hrs = form.cleaned_data.get("av_hr") + (form.cleaned_data.get("av_min")) / 60
                    match_duration = form.cleaned_data.get("match_hr") + (form.cleaned_data.get('match_min')) / 60
                    break_duration = form.cleaned_data.get("break_hr") + (form.cleaned_data.get('break_min')) / 60

                    # count = int(request.POST.get("category_counter"))
                    entered_category = request.POST.getlist('category')
                    print('Categories:', entered_category)
                    logger.debug(request.POST)
                    logger.debug("entered_category:       ", entered_category)
                    all_tournaments = []

                    for i in entered_category:
                        tournament = form.save(commit=False)
                        # tournament.login = user_wrapper
                        # tournament.matches_per_day = (int)(avalaible_hrs / (match_duration + break_duration))
                        # logger.debug("mathes per day" + str(tournament.matches_per_day))
                        # tournament.sport = form.cleaned_data.get('sport')
                        # print("asdfghjklasdfghj" + tournament.sport, form.cleaned_data.get('sport'))
                        type = 1
                        if type_of_match == 'Pool Match':
                            type = 2

                        all_tournaments.append(Tournament(login=user_wrapper, matches_per_day=(int)(
                            avalaible_hrs / (match_duration + break_duration)),
                                                          number_of_team=tournament.number_of_team,
                                                          number_of_pool=tournament.number_of_pool, type=type,
                                                          available_days=tournament.available_days,
                                                          registration_ending=tournament.registration_ending,
                                                          starting_date=tournament.starting_date,
                                                          sport=form.cleaned_data.get('sport'), category=i))

                    print("All:", all_tournaments)

                    Tournament.objects.bulk_create(all_tournaments)

                    # **********************
                    # for i in range(count):
                    #     all_categories.append(
                    #         Category(type=request.POST.get('category' + str(i + 1)), tournament=tournament))
                    # Category.objects.bulk_create(all_categories)
                    # ************************
                    # group1 = []
                    # group2 = []
                    # list1 = []
                    # list2 = []
                    # user_name = user_obj.username

                    # number_of_teams = tournament.number_of_team
                    # number_of_days = tournament.available_days
                    # matches_per_day = tournament.matches_per_day
                    # number_of_pool = tournament.number_of_pool
                    # Our conventions
                    # 1. League matches
                    # 2. Pool System
                    # 3. Knockout

                    # League matches


                    # category.save()
                    print("scheduling")
                    # logger.debug(type)

                    # logger.debug(Pool.objects.filter(login=user_wrapper))
                    # logger.debug(user_wrapper.pool_set.all()   )
                    return HttpResponseRedirect('/dashboard/')
                else:
                    logger.debug("else " + str(form.errors))

            else:
                return render(request, 'home/information.html', {
                    'form': form,
                    'logged_in': True,
                    'error': conf.email_verification_error
                })

        else:
            form = TournamentForm()
            logger.debug('not post in get_information')
        return render(request, 'home/information.html', {
            'form': form,
            'logged_in': True
        })
    else:
        return render(request, 'home/home_page.html', {
            'logged_in': False
        })


def dashboard(request):
    # print(request.user)
    # if str(request.user) == 'AnonymousUser':
    #     return render(request, 'home/register.html', {'form': UserForm, 'info': 'Please Log in First.'})

    user_id = user_logged_in(request)
    logger.debug('dashboard', request.session.get('user', 0))
    if user_id:
        user = User.objects.get(pk=user_id)
        user_wrapper = user.userwrapper
        hosted_tournament = user_wrapper.tournament_set.all()
        number_of_pool = 0
        participated = user_wrapper.team_set.all()
        if hosted_tournament:
            print(hosted_tournament)
            print("Tournament exists")
        print(participated)
        return render(request, 'home/dashboard.html', {
            'logged_in': True,
            'hosted_tournament': hosted_tournament,
            'participated': participated
        })
    else:
        return render(request, 'home/register.html', {
            'logged_in': False,
            'form': UserForm,
            'info': 'Please Log in First.'
        })


def register(request, context={'goto': '/dashboard/'}):
    goto = '/dashboard/'
    logger.debug('register function', request.method, 'context=', context, context.get('goto'), 'request = ', request)
    user_id = request.session.get('user_id', 0)
    if request.method == "POST" and request.POST.get('submit', 0):
        print("register")
        form = UserForm(data=request.POST)
        print(form.errors)
        if form.is_valid():
            new_user = form.save()
            new_user.set_password(new_user.password)
            new_user.save()
            new_user_wrapper = UserWrapper(user=new_user)
            print(new_user.email)
            new_user_wrapper.key = generate_activation_key()
            link = conf.site_initial_link + '/verification/email/' + new_user_wrapper.key + \
                   '/' + new_user.username
            if email_sending_service_enabled:
                send_mail('SpoFit Email Verification',
                          link,
                          'akzarma2@gmail.com',
                          [new_user.email], fail_silently=False)

            new_user_wrapper.save()
            request.session.set_expiry(10 * 60)
            request.session['user_id'] = new_user.id
            # logger.debug('reference = ', ref)
            logger.debug(User.objects.get(pk=new_user.pk).first_name)
            if request.POST.get('goto', 0):
                goto = request.POST.get('goto')
            return HttpResponseRedirect(goto)
        else:
            logger.debug("Form was not valid because of" + str(form.errors))
    else:
        if user_id:
            return HttpResponseRedirect(goto)
        form = UserForm()
        context['form'] = form
        # context['ref'] = ref
        logger.debug(context)

    return render(request, 'home/register.html', context)


def generate_activation_key():
    chars = 'abcdefghijklmnopqrstuvwxyz0123456789'
    secret_key = get_random_string(20, chars)

    return hashlib.sha256((secret_key).encode('utf-8')).hexdigest()


# Works perfectly(Do not touch)
# Convention for pool_number
# 0- To show all available for this tuornament
# 1- To show 1st pool
# 2- To show 2nd pool
# n- to show nth pool
def schedule(request, tournament_number, pool_number=1):
    pool_number = int(pool_number)
    tournament_number = int(tournament_number)
    # For when winner is selected
    if request.is_ajax():
        logger.debug('HeLlO')
        text = request.POST.get('winner_name').split(':')
        match_id = text[1]
        winner = text[0]
        user_id = request.session['user_id']
        user_obj = User.objects.get(id=user_id)
        user_wrapper = user_obj.userwrapper
        logger.debug(winner)
        logger.debug(user_id)
        # if not needed(will review it later)
        if request.is_ajax:
            tournament = user_wrapper.tournament_set.all()
            current_tournament = tournament[tournament_number]
            logger.debug('pool number' + str(pool_number))

home/templates/home/bootstrap.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://fonts.googleapis.com/css?family=Merriweather:900" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet"
          href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.min.css">
    <script src="http://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://apis.google.com/js/platform.js" async defer></script>
    <meta name="google-signin-client_id"
          content="1022111364140-8uhtr1q4rr4r194rbtrfb5iftto8d2mn.apps.googleusercontent.com">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <style>
        body {
            padding-top: 50px;
            background: #F1F1F1;
        }

        #main {
            height: 100%;
            overflow: auto;
        }

        .navbar {
            background: #ad2d35;
        }

        .navbar-custom .navbar-nav > li > a:hover {
            background: #b3000f;
        }

        .navbar-custom .navbar-nav > li > a, .navbar-custom .navbar-brand {
            color: #ffffff;
        }

        .navbar-custom {
            border: #ffffff;
        }

        .selected {
            background: #b3000f;
            color: #FFFFFF !important;
        }

        .nav-pills > li > a {
            color: #000000;
        }

        .navbar-brand {
            font-size: 1.7em;
        }

        .navbar-right {
            margin-right: 15px;
            margin-top: 15px;
            color: #FFFFFF;
        }

        .icon-bar {
            background: #fff;
        }

        .logo-img {
            width: auto;
            height: 20px;
        }

        {% block style %}
        {% endblock %}
    </style>
    {% block head %}
    {% endblock head %}

</head>
<body>

<!--Navbar top-->

<div class="navbar navbar-custom navbar-fixed-top">
    <div class="navbar-header">
        <!--Button NAVBAR toggle-->
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home:home_page' %}"><img class="logo-img"
                                                                       src="{% static 'home/images/logo.png' %}"
                                                                       alt="Spofit logo"></a>
    </div>
    <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
            <li><a href="{% url 'home:home_page' %}">Home</a></li>

            {% if logged_in %}

                <li><a href="{% url 'home:get_information' %}">Add</a></li>
                <li><a href="{% url 'home:view_all_tournament' %}">View Tournaments</a></li>
            {% else %}
                <li><a href="{% url 'home:register' %}">Registration</a></li>
                <li><a href="{% url 'home:view_all_tournament' %}">View Tournaments</a></li>
            {% endif %}

            {#            {% endblock %}#}
            {% block navbar_left %}
            {% endblock %}
        </ul>
        {% block navbar_right %}
        {% endblock %}
    </div>
</div>
{% if error %}
    <div class="alert alert-danger">
        <strong>Error!</strong>
        {% autoescape off %}{{ error }} {% endautoescape %}
    </div>
{% endif %}
{% if info %}
    <div class="alert alert-info">
        {% autoescape off %}{{ info }} {% endautoescape %}
    </div>
{% endif %}
{% if success %}
    <div class="alert alert-success">
        {% autoescape off %}{{ success }} {% endautoescape %}
    </div>
{% endif %}
{% block body %}
{% endblock %}
</body>


<script>
    $(document).ready(function () {
        $('[data-toggle=offcanvas]').click(function () {
            $('.row-offcanvas').toggleClass('active');
        });
    });
</script>
</html>

home/templates/home/dashboard.html
{% extends 'home/bootstrap.html' %}
{% load static %}
{% load widget_tweaks %}
{% block head %}
    <style>
        body, html, .row-offcanvas {
            height: 100%;
        }

        body {
            padding-top: 50px;
            background: #F1F1F1;
        }

        #sidebar {
            width: inherit;
            min-width: 220px;
            max-width: 220px;
            background-color: #F1F1F1;
            float: left;
            height: 100%;
            position: relative;
            overflow-y: auto;
            overflow-x: hidden;
        }

        #main {
            height: 100%;
            overflow: auto;
        }

        /*Media query for small screen toggle*/
        @media screen and (max-width: 768px) {
            .row-offcanvas {
                position: relative;
                -webkit-transition: all 0.25s ease-out;
                -moz-transition: all 0.25s ease-out;
                transition: all 0.25s ease-out;
                width: calc(100% + 220px);
            }

            .row-offcanvas-left {
                left: -220px;
            }

            .row-offcanvas-left.active {
                left: 0;
            }

            .sidebar-offcanvas {
                position: absolute;
                top: 0;
            }
        }

        /*Media query for small screen toggle ENDS*/

        /*Extra style for main contents div*/
        .back {
            background: #ffffff;
            height: 100%;
        }

        .nav-stacked {
            padding-top: 5px;
        }

    </style>
    <script src="https://apis.google.com/js/platform.js?onload=onLoad" async defer></script>
    <script>
        function schedule(obj) {
            var tournament_id = obj.value;
            alert(tournament_id);
            $.ajax({
                type: "POST",
                url: '/start_scheduling/',
                data: {
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                    'tournament_id': tournament_id
                },
                success: function (data) {
                    // grab the inner html of the returned div
                    // so you don't nest a new div#refresh-this-div on every call
                    //var html = $(data).filter('#refresh-this-div').html();
                    //$('#refresh_winner').html(data);
                    alert(data);
                    {#                        snackbar_show(data)#}
                }
            });
        }
    </script>
    <script>
        function signOut() {
            var auth2 = gapi.auth2.getAuthInstance();
            auth2.signOut().then(function () {
                console.log('User signed out.');
            });
        }

        function onLoad() {
            gapi.load('auth2', function () {
                gapi.auth2.init();
            });
        }
    </script>
{% endblock %}
{% block navbar_right %}

    <form action="{% url 'home:logout' %}" method="post">

        {% csrf_token %}
        <div style="margin-top: 15px;margin-right: 5px;float: right">
            <a href="{% url 'home:change_password' %}" style="color: white;text-decoration: none">Change Password</a>
            <button type="submit" name="logout" value="logout" onclick="signOut()"
                    style="color: white;background: none;border: none"><i class="glyphicon glyphicon-user"></i> Logout
            </button>
        </div>
    </form>


{% endblock %}
{% block body %}


    <!--Body with side navbar and main content-->

    <div class="row-offcanvas row-offcanvas-left">
        <!--Sidebar navigation-->
        <div id="sidebar" class="sidebar-offcanvas">
            <div class="col-md-12 back">
                <ul class="nav nav-pills nav-stacked">
                    <li><a class="selected" href="{% url 'home:dashboard' %}">Dashboard</a></li>

                    {#                    {% if number_of_pool > 1 %}#}
                    {#                        <li><a href="{% url 'home:pool_schedule' pool_number=0 %}">Pool</a></li>#}
                    {#                    {% else %}#}
                    {#                        <li><a href="{% url 'home:schedule' %}">Schedule</a></li>#}
                    {#                        <li><a href="#">Points Table</a></li>#}
                    {#                    {% endif %}#}

                    <li><a href="#">Result</a></li>
                    <li><a href="#">Section</a></li>
                    <li><a href="#">F.A.Q</a></li>
                </ul>
            </div>
        </div>
        <!--Main content-->
        <div id="main">
            <div class="col-md-8">
                <!--Toggle for sidebar nav-->

                {% if hosted_tournament %}
                    <h4>Hosted Tournament</h4>
                    {% for each in hosted_tournament %}
                        <a href="{% url 'home:pool_schedule' forloop.counter0 0 %}">Tournament {{ each.sport }} {{ each.category }}</a>
                        {{ each.number_of_team }}
                        <button class="btn btn-danger" onclick="schedule(this)" value={{ each.pk }}>Start</button>
                        <a href="{% url 'home:delete_tournament' each.pk %}">
                            <button class="btn btn-danger" value={{ each.pk }}>Delete</button>
                        </a>
                        <br>
                        <br>
                    {% endfor %}
                {% endif %}
                {% if participated %}
                    <h4><b>Participated</b></h4>
                    {% for each in participated %}
                        {{ each.tournament.sport }}-{{ each.tournament.category }}
                    {% endfor %}
                {% endif %}
                <p class="visible-xs">
                    <button type="button" class="btn btn-danger btn-sm" data-toggle="offcanvas">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                    </button>
                </p>


            </div>

        </div>
    </div>


{% endblock %}

home/templates/home/points_table.html
{% extends 'home/bootstrap.html' %}
{% block style %}
    .thead-inverse{
    background:#b3000f;
    color:#fff;
    }body, html, .row-offcanvas {
    height: 100%;
    }

    body {
    padding-top: 50px;
    background: #f5f5f5;
    }

    #sidebar {
    width: inherit;
    min-width: 220px;
    max-width: 220px;
    background-color: #f5f5f5;
    float: left;
    height: 100%;
    position: relative;
    overflow-y: auto;
    overflow-x: hidden;
    }

    #main {
    height: 100%;
    overflow: auto;
    }

    .navbar {
    background: #ce0010;
    }

    .navbar-inverse .navbar-nav > li > a:hover {
    background: #b3000f;
    }

    .navbar-inverse .navbar-nav > li > a, .navbar-inverse .navbar-brand {
    color: #ffffff;
    }

    .navbar-inverse {
    border: #ffffff;
    }

    .navbar-inverse .navbar-nav > .active > a, .navbar-inverse .navbar-nav > .active > a:hover {
    background: #b3000f;
    }

    .nav-pills > li.active > a, .nav-pills > li.active > a:hover {
    background: #b3000f;
    }

    .nav-pills > li > a {
    color: #000000;
    }

    .bolder {
    font-weight: bolder;
    }

    .wrap {
    background: #fff;
    margin-bottom: 20px;
    }

    .left-border {
    padding: 5px;
    border-left: 3px solid #ce0010;
    }

    .white {
    background: #FFF;
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
    margin-top: 10px
    }

    .back {
    background: #ffffff;
    height: 100%;
    }

    .nav-stacked {
    padding-top: 5px;
    }

    /*
    * off Canvas sidebar
    * --------------------------------------------------
    */
    @media screen and (max-width: 768px) {
    .row-offcanvas {
    position: relative;
    -webkit-transition: all 0.25s ease-out;
    -moz-transition: all 0.25s ease-out;
    transition: all 0.25s ease-out;
    width: calc(100% + 220px);
    }

    .row-offcanvas-left {
    left: -220px;
    }

    .row-offcanvas-left.active {
    left: 0;
    }

    .sidebar-offcanvas {
    position: absolute;
    top: 0;
    }
    }
{% endblock %}
{% block body %}
    <div class="row-offcanvas row-offcanvas-left">
        <div id="sidebar" class="sidebar-offcanvas">
            <div class="col-md-12 back">
                <form action="{% url 'home:schedule' tournament_number %}" method="get">
                    <ul class="nav nav-pills nav-stacked">
                        <li><a href="{% url 'home:dashboard' %}">Dashboard</a></li>
                        {% if number_of_pool > 1 %}
                            <li><a href="{% url 'home:pool_schedule' tournament_number 0 %}">Pool</a></li>
                        {% endif %}
                        <li><a href="{% url 'home:pool_schedule' tournament_number pool_number %}">Schedule</a></li>
                        <li class="active"><a href="{% url 'home:points_table' tournament_number pool_number %}">Points
                            Table</a></li>
                        <li><a href="#">Result</a></li>
                        <li><a href="#">Section</a></li>
                        <li><a href="#">F.A.Q</a></li>
                    </ul>
                </form>
            </div>
        </div>

        <div id="main">
            <div class="col-md-12">
                <p class="visible-xs">
                    <button type="button" class="btn btn-danger btn-sm" data-toggle="offcanvas"><i
                            class="glyphicon glyphicon-chevron-left"></i></button>
                </p>
                <div class="table-responsive">
                    <table class="table table-bordered white">
                        <thead class="thead-inverse">
                        <tr>

                            <th>Team</th>
                            <th>Points</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for team in full_table %}

                            <tr>
                                <td>{{ team.team }}</td>
                                <td>{{ team.wins }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}